# Generated by Django 4.1.2 on 2023-02-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TvShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название фильма"),
                ),
                ("description", models.TextField(verbose_name="Описание фильма")),
                ("image", models.ImageField(upload_to="", verbose_name="Фото")),
                ("trailer", models.URLField(verbose_name="Ссылка с ютуба")),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Колличество серий"),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Horror", "Ужасы"),
                            ("Melodramme", "Мелодрамма"),
                            ("Anime", "Anime"),
                            ("Comedy", "Комедия"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
