# Generated by Django 4.1.5 on 2023-02-27 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tvshow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commet_TV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Введите ваше имя"),
                ),
                ("text", models.TextField(verbose_name="Ваш коммент")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=100,
                        verbose_name="Поставьте оценку",
                    ),
                ),
                (
                    "choise_show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_object",
                        to="tvshow.tvshow",
                    ),
                ),
            ],
        ),
    ]
